spring:
  application:
    name: /
  profiles:
    active: test210
  redis:
    cluster:
      max-redirects: 3
      nodes: 172.16.10.210:7001,172.16.10.210:7002,172.16.10.210:7003
    jedis:
      pool:
         max-idle: 100
         max-total: 600
         max-wait: 1000
    timeout: 3000

server:
  server.context-path: /
  port: 8080
  session-timeout: 60
  tomcat.uri-encoding: UTF-8

datasource:
  type: com.alibaba.druid.pool.DruidDataSource # 使用druid数据源
  write:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://172.16.10.210:3306/lottery_base?useUnicode=true&amp;characterEncoding=utf-8
    username: caipiao
    password: F%46tff%^#@e
  read:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://172.16.10.210:3306/lottery_base?useUnicode=true&amp;characterEncoding=utf-8
    username: caipiao
    password: F%46tff%^#@e


  cache:
    redis:
      namespace: comment

# MyBatis
mybatis:
    typeAliasesPackage: com.fly.caipiao.comment.**.entity
    mapperLocations: classpath*:mapper/**/*.xml
    configuration:
      mapUnderscoreToCamelCase: true

#logger
logging:
  file: logs/message.log
  level:
    root: info
    com.fly.caipiao.comment.mapper: debug


---
spring:
  profiles: dev
server:
  port: 8080
---
spring:
  profiles: test210
server:
  port: 8091
---
spring:
  profiles: test89
server:
  port: 8091
---
spring:
  profiles: prod
server:
  port: 8091

